[colors.cursor]
cursor = "#ffffff"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 16.5

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "0"
mods = "Alt"

[mouse]
hide_when_typing = true

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/bash"

[window]
dynamic_padding = true

[window.dimensions]
columns = 160
lines = 46
