theme = "fleetish_black"

[editor]
scrolloff = 1
auto-format = false
completion-trigger-len = 1
true-color = true
bufferline = "always"

[editor.statusline]
right = ["diagnostics", "selections", "file-type", "file-line-ending", "file-encoding", "position"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
"A-f" = ":format"
"space" = { "c" = ":buffer-close" }

[keys.insert]
"A-f" = ":format"
"j" = { "k" = "normal_mode" }
