[language-server.ltex-ls]
command = "ltex-ls"

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "cairo"
formatter = { command = "cairo-format" , args = ["-"] }

[[language]]
name = "graphql"
formatter = { command = "prettier" , args = ["--parser", "graphql"] }

[[language]]
name = "html"
formatter = { command = "prettier" , args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = "prettier" , args = ["--parser", "json"] }

[[language]]
name = "ltex"
scope = "source.ltex"
file-types = []
roots = []
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook", "mdx"]
formatter = { command = "prettier" , args = ["--parser", "markdown"] }

[[language]]
name = "python"
formatter = { command = "black" , args = ["-"] }

[[language]]
name = "solidity"
formatter = { command = "forge" , args = ["fmt", "-r", "-"] }

[[language]]
name = "tsx"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "yaml"
formatter = { command = "prettier" , args = ["--parser", "yaml"] }
