[[language]]
name = "cairo"
formatter = { command = "cairo-format" , args = ["-"] }

[[language]]
name = "html"
formatter = { command = "prettier" , args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = "prettier" , args = ["--parser", "json"] }

[[language]]
name = "ltex"
scope = "source.ltex"
file-types = []
roots = []
language-server = { command = "ltex-ls" }

[[language]]
name = "markdown"
formatter = { command = "prettier" , args = ["--parser", "markdown"] }

[[language]]
name = "python"
formatter = { command = "black" , args = ["-"] }

[[language]]
name = "rust"
config = { checkOnSave = { command = "clippy" } }

[[language]]
name = "solidity"
formatter = { command = "forge" , args = ["fmt", "-r", "-"] }

[[language]]
name = "tsx"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "yaml"
formatter = { command = "prettier" , args = ["--parser", "yaml"] }
