[[language]]
name = "cairo"
formatter = { command = "cairo-format" , args = ["-"] }

[[language]]
name = "json"
formatter = { command = "prettier" , args = ["--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = "prettier" , args = ["--parser", "markdown"] }

[[language]]
name = "tsx"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier" , args = ["--parser", "typescript"] }

[[language]]
name = "yaml"
formatter = { command = "prettier" , args = ["--parser", "yaml"] }
