[language-server.ltex-ls]
command = "ltex-ls"

[language-server.scarb-ls]
command = "scarb"
args = ["cairo-language-server"]

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.typescript]
updateImportsOnFileMove = { enabled = "always" }
suggest = { completeFunctionCalls = true }

[[language]]
name = "cairo"
formatter = { command = "cairo-format" , args = ["-"] }
language-servers = [ "scarb-ls" ]

[[language]]
name = "graphql"
formatter = { command = "biome", args = ["check", "--fix", "--stdin-file-path", "test.graphql"] }

[[language]]
name = "html"
formatter = { command = "prettier" , args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "biome", args = ["check", "--fix", "--stdin-file-path", "test.js"] }

[[language]]
name = "json"
formatter = { command = "prettier" , args = ["--parser", "json"] }

[[language]]
name = "ltex"
scope = "source.ltex"
file-types = []
roots = []
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook", "mdx"]
formatter = { command = "prettier" , args = ["--parser", "markdown"] }

[[language]]
name = "python"
formatter = { command = "black" , args = ["-"] }

[[language]]
name = "solidity"
formatter = { command = "forge" , args = ["fmt", "-r", "-"] }

[[language]]
name = "tsx"
formatter = { command = "biome", args = ["check", "--fix", "--stdin-file-path", "test.tsx"] }

[[language]]
name = "typescript"
formatter = { command = "biome", args = ["check", "--fix", "--stdin-file-path", "test.ts"] }

[[language]]
name = "yaml"
file-types = ["yml", "yaml", { glob = ".kube/config" }]
formatter = { command = "prettier" , args = ["--parser", "yaml"] }
